### PR TITLE
Remap some keys and map Q,W,E,A,S,D,Z,C to full movement with diagonals

### PR DESCRIPTION
**Pull request by prurigro**
Like most laptops these days, mine doesn't have a numpad, which means that I currently can't move diagonally without resorting to the mouse. I tried playing with a number of alternative solutions that worked around the current mappings, but when none were very comfortable to play with, I opted to move things around a bit and eventually found something I liked. I'll explain where everything's been moved below, and if you do agree with the logic behind adding the complete set of directional mappings, I encourage encourage you to tweak what I've done before merging :)

**Edit**: I pushed a second commit after some additional playing around, and it changes the search key from its previous updated mapping **L** to **F**, as well as adding the _pick up/interact_ function tied to the **ENTER** key to the **X** key as well. With these tweaks, I can use a single hand to control the game about 90% of the time.

On a side note, do you think it would be worth it to add optional custom mappings through the config?
# Updated Mappings
## BEFORE

The previous keyboard layout is shown below, with keys that don't have any functions assigned to them shown by their letter, and ones that have been assigned replaced by underscores:

```
_ w e _ t y u _ o p
 _ _ d f g _ _ k l
   z x _ _ b n m
```
## AFTER

Below is the updated keyboard layout from this pull request, following the same logic as the diagram above, but with the addition of stars to show the new movement keys:

```
* * * _ t y u _ _ p
 * * * _ g h j _ l
   * _ * _ b n m
```
### New Movement Keys

These are the new directional key mappings for `Q,W,E,A,S,D,Z,C`:

|  | Key |  |  | Direction |  |
| :-: | :-: | :-: | :-: | :-: | :-: |
| Q | W | E | UpLeft | Up | UpRight |
| A | S | D | Left | Down | Right |
| Z |  | C | DownLeft |  | DownRight |
### Updated Function Keys

| Function | From | To |
| :-- | :-: | :-: |
| Quickslot | **Q** | **O** |
| Attack | **A** | **K** |
| Search | **S** | **L** |
| Status | **H** | **F1** |
| Catalogue | **C** | **F2** |
| Journal | **J** | **F3** |
### Additional Tweaks

The **X** key now performs the same action as **ENTER** during gameplay.

Cheers!

### CODE REVIEW

**Comment by Arcnor** [comment]
Sorry, forgot to comment on this one.

The only problem I see with this is non-QWERTY layouts, although that happens with every game that supports the WSAD movement.

We should definitely have key remapping at some point.

What do you think @watabou ?

**Comment by watabou** [comment]
Well, for me the current layout is more comfortable:) Its pros:
- The keys are more intuitive: **A** for attack, **S** for search etc.
- It is easy to use with a mouse: frequently used keys are on the left side of keyboard

But of course I understand @prurigro's argument. I think, that we need a "Keyboard setting" window, where every player could remap keys for himself. Is it what you were talking about, @Arcnor?

**Comment by prurigro** [comment]
Yeah, diagonal movement is pretty important for both battle tactics as well as to reduce food consumption, so some solution would be ideal, but I like your idea much more than the one I presented @watabou; providing an option to configure custom keymappings definitely sounds like the ideal solution.

@Arcnor & @watabou: It should be fairly simple to replace the hard-coded values with equivalent private variables that get initialized with the same values, and once that's working, a function to check `pd-prefs` for keymap settings could be added that would override the default values of the variables that associated settings were found for or something? Not that either of you wouldn't know how to implement this on your own, but I figured I'd try shooting some ideas out to get the juices flowing. Thoughts?

I'll leave this pull request open until @Arcnor sees @watabou 's reply, but I'm definitely not expecting it to get pulled at this point.

On a side note, I thew up a **pixel-dungeon** package for Archlinux on the [AUR](https://aur.archlinux.org/packages/pixel-dungeon-git/), if either of you happen to run Arch you should give it a try :)

**Comment by Arcnor** [comment]
Quick reply (I'm on mobile)

I've been working on a key remapping dialog that should keep everyone
happy, I'll push as soon as I have everything working

**Comment by prurigro** [comment]
@Arcnor: Awesome! I'll close this up now- thanks :)

**Pull request closed without merging**
