### PR TITLE
Update to 1.7.2a

### PR DESCRIPTION
**Pull request by prurigro**
Hey there- you might have been working on this yourself, but I managed to get 1.7.2a working in pixel-dungeon-gdx, with the only issue so far that I've run into being some glitches in the character selection screen. I figured I'd offer where I've managed to get to so far in case it's of any help :)

The commits are split into upstream 1.7.1c->1.7.2a diffs that patched without intervention, followed by the diffs I had to tweak things for each of the upstream commits, and my own additional changes that needed to be made to get things going which I attempted to separate by category (the removal of immersive mode for example).

Cheers!

### CODE REVIEW

**Comment by prurigro** [comment]
Aha- I fixed the issue with the character selection screen!

**Comment by prurigro** [comment]
Hey- just popping in to add that since the update I've played the game through from start to finish without running into any issues

**Comment by insert3coins** [comment]
isn't it missing the new mode gameplay? ( Immersive mode, under settings ) 

also missing challenges

**Comment by prurigro** [comment]
I'd done the changes then exported as a patch before re-patching fresh sources on a different box (with my github account's ssh pubkey), and I just realized `git format-patch` doesn't export binary changes, so I pushed an update that included the updated (and new) assets just now.

@tehface: **Immersive** mode is Android-specific and would need to be reimplemented (on a conditional basis when android is detected, I assume) for **libgdx**, which I'm not familiar enough with to have done so myself, so I isolated its removal in [this commit](https://github.com/prurigro/pixel-dungeon-gdx/commit/845c02d0e02bba0f2e73fa89c949bfa53779a289) to make it easy to reimplement.

In respect to challenges; they weren't showing up because the assets hadn't been pulled into the commit, which I noticed thanks to you! I just tested with the updated assets, and the button now shows up and works-- thanks for pointing that out!

Cheers

**Comment by insert3coins** [comment]
brilliant glad i was able to help :D

**Comment by prurigro** [comment]
I just pushed an additional commit that's unrelated to 1.7.2a, but it fixes the remaining issues with pressing both mouse buttons while it's sliding, which turns out to have been happening because sliding an input device with two separate inputs pressed simultaneously appears to meet the criteria for potentially then performing pinch to zoom, and maybe it would even make sense on some hybrid devices like clickpads? With a mouse though, the variables used to measure the distance between the fingerers are perpetually 0, and this becomes problematic when that particular function divides by one of those values to determine how much to zoom... Anyway, this commit prevents the function from being triggered when it's going to divide by zero, which seems like a good idea in general (even if there's a better solution to fix the mouse, specifically), so if you end up not pulling this request @Arcnor, you should still look at/potentially grab this one commit.

**Comment by Arcnor** [comment]
Sorry for not replying earlier, Real Life (tm) took over :smile: 

I think @watabou is going to take care of this one. And yes, it will impact somehow with the work I was doing on I18N, and that's a shame, but I guess it's more important to get 1.7.2 out there.

**Comment by prurigro** [comment]
@Arcnor: Sounds good minus having to redo some of the I18N stuff-- maybe it'd be worth coordinating this with watabou to implement upstream in the one-release-ahead playstore version? Otherwise, I picture all the work on this being reset each version bump on git. I hear ya on the occasional real life btw :)

@watabou: I've been playing pixel-dungeon-gdx 1.7.2a semi-regularly for ~17 days now, including numerous save swaps with the phone version (my build has the encryption patched out for compatibility reasons), and since fixing the missing-assets issue pointed out by tehface, I haven't run into any issues in respect to the version bump. I've had the 1.7.2a update on my [ArchLinux AUR package](https://aur.archlinux.org/packages/pixel-dungeon-git/) for pixel-dungeon too, and I haven't had any comments as to issues with it either. I also gave the shattered-pixel-dungeon fork a hand porting their 1.7.2-based release to the gdx fork ([available here](https://github.com/00-Evan/shattered-pixel-dungeon-gdx)), starting from this pull request, and I didn't bump into anything I forgot to pull in there either. This doesn't mean there were no issues of course, but I feel like they'd have to be relatively obscure to have slipped in. Also, on a side note, I'm not familiar enough with Android input processing to know if that divide-by-zero issues I fixed in the second most recent commit would be worth bringing upstream, but I it seems like it might be if 0 is in the range, even if extremely improbable.

Cheers!

**Comment by watabou** [comment]
@prurigro Yeah, everything works perfectly, thanks a lot! The only issue I've noticed is about ctrl-clicking the map and buttons, I'll have a look at this.

**Pull request merged**
